//
//  JsonArrayObjectsUnitTesting.swift
//  AFoundationUnitTesting
//
//  Created by Ihor Myroniuk on 04.10.2020.
//  Copyright Â© 2020 Ihor Myroniuk. All rights reserved.
//

import XCTest
import Foundation
@testable import AFoundation

class JsonArrayObjectsUnitTesting: XCTestCase {
//
//    func testArrayObjects() {
//        let booleans = [JsonObject(), JsonObject(), JsonObject()]
//        var array = JsonArray()
//        for boolean in booleans {
//            array.append(boolean)
//        }
//        
//        do {
//            let arrayBooleans = try array.arrayObjects()
//            
//            XCTAssert(arrayBooleans == booleans, "Object returned unexpected arrayObjects \"\(String(describing: arrayBooleans))\" while arrayObjects \"(\(String(describing: booleans))\" is expected)")
//        } catch {
//            XCTFail("Unexpected error \(error) is thrown")
//        }
//    }
//    
//    func testNotArrayObjects() {
//        let notBooleans: [JsonValue] = [JsonObject(), "string2", JsonObject()]
//        var array = JsonArray()
//        for notBoolean in notBooleans {
//            array.append(notBoolean)
//        }
//        
//        do {
//            let arrayBooleans = try array.arrayObjects()
//            
//            XCTFail("Error \(JsonErrorNotArrayObjects.self) has to be thrown, but arrayObjects \"\(String(describing: arrayBooleans))\" is returned")
//        } catch _ as JsonErrorNotArrayObjects {
//            
//        } catch {
//            XCTFail("Unexpected error \(error.self) is thrown")
//        }
//    }
//    
}

